image: maven:3-jdk-8

image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s maven_settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=maven_settings.xml"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile