image: maven:latest

stages:
  - build
  - deploy
  - clean


variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

before_script:
  - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                            https://maven.apache.org/xsd/settings-1.0.0.xsd">
                <proxies>
                    <proxy>
                        <active>true</active>
                        <host>10.0.1.8</host>
                        <port>8000</port>
                </proxy>                
                </proxies>
                <servers>
                    <server>
                        <id>StagingServer8888</id>
                        <username>tomcat</username>
                        <password>s3cret</password>
                    </server>
                    <server>
                        <id>ProductionServer8889</id>
                        <username>tomcat</username>
                        <password>s3cret</password>
                    </server>                
                </servers>
          </settings>' > $HOME/.m2/settings.xml
clean:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
    
  artifacts:
    paths:
    - target/*.war
    expire_in: 1 week


deploy_staging:
  stage: deploy
  script:
     - mvn $MAVEN_CLI_OPTS -Dtomcat-server-url=http://10.0.1.63:8888/manager/text -Dtomcat-server-name=StagingServer8888 tomcat7:redeploy 
  environment:
    name: staging
    url: http://10.0.1.63:8888/tail2web/
  only:
  - master

deploy_production:
  stage: deploy
  script:
     - mvn $MAVEN_CLI_OPTS -Dtomcat-server-url=http://10.0.1.63:8889/manager/text -Dtomcat-server-name=ProductionServer8889 tomcat7:redeploy 
  environment:
    name: production
    url: http://10.0.1.63:8889/tail2web/
  only:
  - master
  when: manual 

undeploy_staging:
  stage: clean
  when: manual 
  script:
    - mvn $MAVEN_CLI_OPTS -Dtomcat-server-url=http://10.0.1.63:8888/manager/text -Dtomcat-server-name=StagingServer8888 tomcat7:undeploy
  environment:
    name: staging
    url: http://10.0.1.63:8888/tail2web/

undeploy_production:
  stage: clean
  when: manual 
  script:
    - mvn $MAVEN_CLI_OPTS -Dtomcat-server-url=http://10.0.1.63:8889/manager/text -Dtomcat-server-name=ProductionServer8889 tomcat7:undeploy 
  environment:
    name: production
    url: http://10.0.1.63:8889/tail2web/