image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
    
  artifacts:
    paths:
    - target/*.war
    expire_in: 1 week


undeploy_staging:
  when: manual 
  script:
    - mvn $MAVEN_CLI_OPTS tomcat7:undeploy


deploy_staging:
  stage: deploy
  script:
     - mvn $MAVEN_CLI_OPTS tomcat7:redeploy
  environment:
    name: staging
    url: http://10.0.1.63:8888/tail2web/
  only:
  - master
